[package]
name = "raft-example"
version = "0.1.0"
authors = ["siddontang <siddontang@gmail.com>"]

[dependencies]
raft = "0.1"
sled = "0.15.13"
log = "0.4"
clap = "2.31.1"
rocket = "0.3.6"
rocket_codegen = "0.3.6"